name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Deno setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check
        run: deno task check
      
      - name: Publish
        run: deno publish
